/**
 * Created by admini on 2016/10/19.
 */

export const CHANGE_NAME = 'CHANGE_NAME';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const AJAX_LOGIN_REQUEST = 'AJAX_LOGIN_REQUEST';
export const AJAX_LOGIN_SUCCESS = 'AJAX_LOGIN_SUCCESS';
export const AJAX_LOGIN_FAILURE = 'AJAX_LOGIN_FAILURE';
export const LOG_OUT = 'LOG_OUT';

export const AJAX_CLASS_LIST_REQUEST = 'AJAX_CLASS_LIST_REQUEST';
export const AJAX_CLASS_LIST_SUCCESS = 'AJAX_CLASS_LIST_SUCCESS';
export const AJAX_CLASS_LIST_FAILURE = 'AJAX_CLASS_LIST_FAILURE';
export const CHANGE_CLASS_LIST_PAGE = 'CHANGE_CLASS_LIST_PAGE';

export const AJAX_STUDENT_LIST_REQUEST = 'AJAX_STUDENT_LIST_REQUEST';
export const AJAX_STUDENT_LIST_SUCCESS = 'AJAX_STUDENT_LIST_SUCCESS';
export const AJAX_STUDENT_LIST_FAILURE = 'AJAX_STUDENT_LIST_FAILURE';
export const CHANGE_STUDENT_LIST_PAGE = 'CHANGE_STUDENT_LIST_PAGE';

export const AJAX_TEACHER_LIST_REQUEST = 'AJAX_TEACHER_LIST_REQUEST';
export const AJAX_TEACHER_LIST_SUCCESS = 'AJAX_TEACHER_LIST_SUCCESS';
export const AJAX_TEACHER_LIST_FAILURE = 'AJAX_TEACHER_LIST_FAILURE';
export const CHANGE_TEACHER_LIST_PAGE = 'CHANGE_TEACHER_LIST_PAGE';

export const AJAX_ROLE_LIST_REQUEST = 'AJAX_ROLE_LIST_REQUEST';
export const AJAX_ROLE_LIST_SUCCESS = 'AJAX_ROLE_LIST_SUCCESS';
export const AJAX_ROLE_LIST_FAILURE = 'AJAX_ROLE_LIST_FAILURE';
export const CHANGE_ROLE_LIST_PAGE = 'CHANGE_ROLE_LIST_PAGE';







